config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  get 'recipe_foods/new'
  get 'recipe_foods/create'
  get 'recipe_foods/edit'
  get 'recipe_foods/destroy'
  resources :foods
  resources :recipes
  resources :public_recipes, only: [:index]
  resources :food_recipes
  devise_for :users
  resources :users, only: [:index, :show]
  resources :shopping_list, only: [:index]
  root to: "users#index"
end

app/models/public_recipe.rb
class PublicRecipe < ApplicationRecord
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = Recipe.all
  end
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/views/public_recipes/_form.html.erb
<%= form_with(model: public_recipe) do |form| %>
  <% if public_recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(public_recipe.errors.count, "error") %> prohibited this public_recipe from being saved:</h2>

      <ul>
        <% public_recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.text_field :index %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/public_recipes/_public_recipe.html.erb
<div id="<%= dom_id public_recipe %>">
  <p>
    <strong>Index:</strong>
    <%= public_recipe.index %>
  </p>

  <div>
    <p>Total food items: <%= %></p>
    <p>Total price: <%= %></p>
  </div>
</div>

app/views/public_recipes/edit.html.erb
<h1>Editing public recipe</h1>

<%= render "form", public_recipe: @public_recipe %>

<br>

<div>
  <%= link_to "Show this public recipe", @public_recipe %> |
  <%= link_to "Back to public recipes", public_recipes_path %>
</div>

app/views/public_recipes/index.html.erb
<div style="">
  <h1 style="font-weight: bold; text-align: center; ">Public Recipes</h1>

  <div id="recipes">
    <% if @recipes.empty? %>
      <p class="" style="font-weight: bold; margin: 10px;">No recipes available! </p>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div class="a" style="border: 1px solid #ccc; padding: 10px; margin: 10px;">
          <div class="one">
            <h2 style="font-weight: bold;"><%= recipe.name %></h2>
            <% if can? :delete, recipe %>
              <%= button_to "Destroy this recipe", recipe, method: :delete, style: "font-weight: bold;" %>
            <% end %>
            <p>
              <%= link_to "Show", recipe, class: "btn btn-primary", style: "font-weight: bold; text-decoration: none; margin-right: 10px;" %>
            </p>
          </div>
            
          <div>
            <p><%= recipe.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/public_recipes/new.html.erb
<h1>New public recipe</h1>

<%= render "form", public_recipe: @public_recipe %>

<br>

<div>
  <%= link_to "Back to public recipes", public_recipes_path %>
</div>

app/views/public_recipes/show.html.erb
<div>
  <div>
    <%= link_to recipes_path(@recipe.id) do %>
      <h3><%= @recipe.name %></h3>
    <% end %>
    <p>By: <%= @recipe.user.name %></p>
  </div>

  <div>
    <p>Total food items: <%= @recipe.foods.count %></p>
    <p>Total price: <%= calculate_total_price(@recipe.foods) %></p>
  </div>
</div>