config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  get 'recipe_foods/new'
  get 'recipe_foods/create'
  get 'recipe_foods/edit'
  get 'recipe_foods/destroy'
  resources :foods
  resources :recipes
  resources :public_recipes, only: [:index]
  resources :food_recipes
  devise_for :users
  resources :users, only: [:index, :show]
  resources :shopping_list, only: [:index]
  root to: "users#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attr_accessor :public

  before_save :set_public

  belongs_to :user, foreign_key: :user_id
  has_many :food_recipes, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :description, presence: true
  validates :public, presence: true

  private

  def set_public
    self.public ||= false
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @foods = current_user.foods.joins(:food_recipes).where(food_recipes: { recipe_id: @recipe.id })
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH /recipes/1/toggle or /recipes/1/toggle.json
  def toggle
    @recipe.toggle!(:public)
    redirect_to recipe_path(@recipe), notice: 'Recipe was successfully updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = current_user.recipes.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div>
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>

    </div>
  <% end %>
  <div class="field">
    <%= form.label :Name %><br />
    <%= form.text_field :name, placeholder: "Enter recipe name" %>
  </div>
  <div class="field">
    <%= form.label :"Preparation Time" %><br />
    <%= form.text_field :preparation_time, placeholder: "Enter preparation time" %>
  </div>
  <div class="field">
    <%= form.label :Description %><br />
    <%= form.text_area :description, placeholder: "Enter recipe description" %>
  </div>
  <div class="field">
    <%= form.label :Public %><br />
    <%= form.label :public, "YES", value: "true"  %>
    <%= form.radio_button :public, true, checked: true %>
    <%= form.label :public, "NO", value: "false" %>
    <%= form.radio_button :public, false %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag 'recipe', media: 'all', 'data-turbolinks-track': 'reload' %>
<div>
  <h1 class="recipe-title">Recipes</h1>

  <div class="recipes">
    <% if @recipes.empty? %>
      <p class="">No recipes available! </p>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div class="recipe-item">
          <div class="recipe-header">
            <div>
                <div class="recipe-info" style="display:flex; gap:70%; align-items:center">
                  <p><%= recipe.name %></p>
                  <p><%= recipe.description %></p>
                </div>
                <div style="display:flex; gap:70%; align-items:center">
                  <% if can? :delete, recipe %>
                    <%= button_to "Destroy this recipe", recipe, method: :delete %>
                  <% end %>
              </div> <p>
              <%= link_to "View Recipe", recipe, class: "view-recipe-button" %>
             </p>
            </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to "Add Recipe", new_recipe_path %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag 'recipe', media: 'all', 'data-turbolinks-track': 'reload' %>


<div class="container" style="background-color: #f0f0f0; padding: 20px; border: 1px solid #ccc; display: flex; flex-direction:column;">
    <div class="recipe-details">
      <h2 style="font-weight: bold; text-align: center;"><%= @recipe.name %></h2>
      <div class="">
        <p style="font-weight: bold;">Preparation time: <%= @recipe.preparation_time %> hours</p>
        <p style="font-weight: bold;"><%= @recipe.description %></p>
      </div>
    </div>

    <div class="second_table_recipes" style="display: flex; gap: 70%; align-items: center; margin-top: 10px;">
      <div class="button_action">
        <%= link_to "Generate Shopping List", food_recipes_path, class: 'button', style: 'font-weight: bold; text-decoration: none;' %>
      </div>
      <div class="button_action">
        <%= button_to "Add Ingredient", new_food_recipe_path, method: :get, class: "button", style: 'font-weight: bold;' %>
      </div>
    </div>

    <table class="grid-container2" style="margin-top: 20px;">
      <tr style="font-weight: bold;">
        <td>Food</td>
        <td>Unit Price</td>
        <td>Quantity</td>
        <td>Actions</td>
      </tr>
      <% if @foods.empty? %>
      <% else %>
      <% @foods.each_with_index do |food, index| %>
      <% row_class = index.even? ? 'even-row' : 'odd-row' %>
      <tr class="<%= row_class %>">
        <td><%= food.name %></td>
        <td>$<%= food.price %></td>
        <td><%= food.quantity %><%= food.measurement_unit %></td>
        <td>
          <%= button_to "Edit", edit_food_path(food.id), method: :get, class: 'edit_btn', style: 'font-weight: bold;' %> |
          <%= button_to "Delete", food_path(food.id), method: :delete, class: 'delete_btn', style: 'font-weight: bold;' %>
        </td>
      </tr>
      <% end %>
      <% end %>
    </table>

    <div class="button_action" style="text-align: center; margin-top: 20px;">
      <%= link_to "Back to recipes", recipes_path, style: 'font-weight: bold; text-decoration: none;' %>
    </div>
</div>