config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  get 'recipe_foods/new'
  get 'recipe_foods/create'
  get 'recipe_foods/edit'
  get 'recipe_foods/destroy'
  resources :foods
  resources :recipes
  resources :public_recipes, only: [:index]
  resources :food_recipes
  devise_for :users
  resources :users, only: [:index, :show]
  resources :shopping_list, only: [:index]
  root to: "users#index"
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/controllers/food_recipes_controller.rb
# app/controllers/food_recipes_controller.rb

class FoodRecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food_recipe

  # GET /food_recipes or /food_recipes.json
  def index
    @foods = Food.joins(:food_recipes).where(user_id: current_user.id)
    @food_count = @foods.length
    @food_cost = @foods.sum(:price)
  end

  # GET /food_recipes/1 or /food_recipes/1.json
  def show; end

  # GET /food_recipes/new
  def new
    @food_recipe = FoodRecipe.new
  end

  # GET /food_recipes/1/edit
  def edit; end

  # POST /food_recipes or /food_recipes.json
  def create
    @food = Food.find_by(name: params[:category])
    @food_id = @food.id
    @food_recipe = FoodRecipe.new(recipe_id: params[:id], food_id: @food_id,
                                  quantity: food_recipe_params[:quantity].to_i)

    if @food_recipe.save
      redirect_to recipe_path
    else
      render :new
    end
  end

  # PATCH/PUT /food_recipes/1 or /food_recipes/1.json
  def update
    respond_to do |format|
      if @food_recipe.update(food_recipe_params)
        format.html { redirect_to food_recipe_url(@food_recipe), notice: 'Food recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_recipes/1 or /food_recipes/1.json
  def destroy
    @food_recipe.destroy

    respond_to do |format|
      format.html { redirect_to food_recipes_url, notice: 'Food recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_food_recipe
    @food_all = Food.where(user_id: current_user.id)
    # @food_recipe = FoodRecipe.find(params[:id])
    # @foods = Food.where(user_id: current_user.id)
  end

  private

  # Only allow a list of trusted parameters through.
  def food_recipe_params
    params.require(:food_recipe).permit(:category, :quantity)
  end
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/views/food_recipes/_form.html.erb
<%= form_with(model: food_recipe) do |form| %>
  <%= select_tag :category, options_for_select(@food_all.map { |food| food.name }) %>
   <div class="field">
      <%= form.label :quantity %><br />
      <%= form.text_field :quantity, autofocus: true, autocomplete: "quantity" %>
    </div>
      <div class="actions">
      <%= form.submit "Add" %>
    </div>
  <% end %>

app/views/food_recipes/edit.html.erb
<h1>Editing food recipe</h1>

<%= render "form", food_recipe: @food_recipe %>

<br>

<div>
  <%= link_to "Show this food recipe", @food_recipe %> |
  <%= link_to "Back to food recipes", food_recipes_path %>
</div>

app/views/food_recipes/food_recipe.html.erb
<div id="<%= dom_id food_recipe %>">
</div>

app/views/food_recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<section class="shopping_list" style="padding:20px; border: 1px solid #ccc;">
  <h1 class="shopping_list_text" style="text-align: center;">Shopping List</h1>
  <div class="things_to_buy">
    <p>Amount of Food Items to buy: <%= @food_count %></p>
    <p>Total Value of Food Needed: $<%= @food_cost %></p>
  </div>
  <table class="grid-container3" style="margin-top: 20px; width: 100%;">
    <tr style="font-weight: bold;">
      <td>Food</td>
      <td>Unit Price</td>
      <td>Quantity</td>
    </tr>
    <% if @foods.empty? %>
    <% else %>
      <% @foods.each_with_index do |food, index| %>
        <% row_class = index.even? ? 'even-row' : 'odd-row' %>
        <tr class="<%= row_class %>">
          <td><%= food.name %></td>
          <td>$<%= food.price %></td>
          <td><%= food.quantity %><%= food.measurement_unit %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</section>

app/views/food_recipes/new.html.erb
<h1>New food recipe</h1>

<%= render "form", food_recipe: @food_recipe %>

<br>

<div>
  <%= link_to "Back to food recipes", food_recipes_path %>
</div>

app/views/food_recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food_recipe %>

<div>
  <%= link_to "Edit this food recipe", edit_food_recipe_path(@food_recipe) %> |
  <%= link_to "Back to food recipes", food_recipes_path %>

  <%= button_to "Destroy this food recipe", @food_recipe, method: :delete %>
</div>