config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  get 'recipe_foods/new'
  get 'recipe_foods/create'
  get 'recipe_foods/edit'
  get 'recipe_foods/destroy'
  resources :foods
  resources :recipes
  resources :public_recipes, only: [:index]
  resources :food_recipes
  devise_for :users
  resources :users, only: [:index, :show]
  resources :shopping_list, only: [:index]
  root to: "users#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :food_recipes
  has_many :recipes, through: :food_recipes

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :unit_price, numericality: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.includes(:user).all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    puts food_params
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :unit_price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>food:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

    <p>
    <strong>unit price:</strong>
    $<%= food.unit_price %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :food, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :unit_price, style: "display: block" %>
    <%= form.text_field :unit_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'food', media: 'all', 'data-turbolinks-track': 'reload' %>

<p style="color: green"><%= notice %></p>

<div class="table-info">

<div class="new-food-container">
  <%= link_to "ADD FOOD", new_food_path, class: "new-food" %>
</div>

<table border="2">
  <tr>
    <th>Food</th>
    <th>Measurement Unit</th>
    <th>Unit Price</th>
    <th>Actions</th>
  </tr>
  <% @foods.each do |food| %>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td>$<%= food.unit_price %></td>
      <td>
        <%# <%= link_to "Show", food %> 
        <%# <%= link_to "Edit", edit_food_path(food) %> 
        <%= link_to "Delete", food, method: :delete, data: { confirm: "Are you sure?" }, class: "delete-food" %>
      </td>
    </tr>
  <% end %>
</table>
<div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>